#!/bin/bash

SELECTION=$(man -k '.' | sort | bemenu -l 10 -p 'Select manpage' -i)

NAME=$(awk '{print $1}' <<<$SELECTION)
SECTION=$(awk '{gsub(/[()]/, ""); print $2}' <<<$SELECTION)

if [[ -n $NAME && -n $SECTION ]]; then
  man -Tps "$SECTION" "$NAME" | ps2pdf - | zathura -
else
  exit 1
fi
