#!/bin/bash

# Name regex: ^[\w:\-.]+
# Section regex: \(\w+\)
# Both regex: ^[\w:\-.]+\s\(\w+\)

#man -k . | column -t | dmenu -l 20 -fn 'Jua-14' | awk '{print $1}' | xargs -r man -Tpdf | zathura -

SELECTION=$(man -k '.' | sort | bemenu -l 10 -p 'Select manpage' -i)

NAME=$(awk '{print $1}' <<<$SELECTION)
SECTION=$(awk '{gsub(/[()]/, ""); print $2}' <<<$SELECTION)

if [[ -n $NAME && -n $SECTION ]]; then
  man -Tps "$SECTION" "$NAME" | ps2pdf - | zathura -
else
  exit 1
fi
